[package]
name = "game_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = { workspace = true }
glam = { workspace = true }
tracing = { workspace = true }
wgpu = "0.18"
winit = {version = "0.29", features = ["rwh_06", "rwh_05"]}

[dev-dependencies]
color-eyre = { workspace = true }
pollster = { workspace = true }
tracing-subscriber = { workspace = true }
