[package]
name = "experimental"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comfy = { version = "0.3.1", features = ["wayland"] }
egui = "0.24.1"
env_logger = "0.10.1"
