[workspace]
members = ["app", "physics", "game_engine"]
resolver = "2"

[workspace.dependencies]
glam = "0.25"
tracing = "0.1"
tracing-subscriber = {version = "0.3", features = ["env-filter"]}
pollster = "0.3"
eyre = "0.6"
color-eyre = "0.6"
