[package]
name = "experimental"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comfy = "0.3"
egui = "0.24"
env_logger = "0.10"
# comfy 0.3 uses glam 0.24
glam = "0.24"
physics = { path = "../physics" }