permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: build
jobs:
  nightly-build:
    runs-on: ubuntu-latest
    name: nightly build
    steps:
      - name: Install system dependencies
        run: sudo apt-get install -y libwayland-dev libasound2-dev libxkbcommon-dev
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install nightly
        uses: dtolnay/rust-toolchain@nightly
      - name: cargo build --release --all-targets
        run: cargo build --release --all-targets
      - uses: actions/upload-artifact@v4
        with:
          path: target/release/experimental
          if-no-files-found: error
